name: bit-thesis
channels:
  - defaults
  - conda-forge
  - nvidia
  - iopath
  - bottler
  - pytorch
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - aom=3.12.1
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=13.1.115
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=13.1.115
  - cuda-nsight-compute=12.4.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=13.1.115
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.4.127
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.4.127
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=13.1.118
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-version=13.1
  - cuda-visual-tools=11.6.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.3
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.16
  - fvcore=0.1.5.post20221221
  - gds-tools=1.16.1.26
  - giflib=5.2.2
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2023.0.0
  - iopath=0.1.9
  - jpeg=9f
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.16.1.26
  - libcufile-dev=1.16.1.26
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnsl=2.0.0
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - nsight-compute=2025.4.1.2
  - nspr=4.37
  - nss=3.117
  - nvidiacub=1.10.0
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - portalocker=3.0.0
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.25
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytorch3d=0.7.5
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tabulate=0.9.0
  - tbb=2021.8.0
  - termcolor=3.1.0
  - tesseract=5.2.0
  - tk=8.6.15
  - torchvision=0.14.0
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - click==8.1.8
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.16
      - kagglehub==0.3.13
      - kiwisolver==1.4.7
      - loguru==0.7.3
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - multidict==6.7.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nump==5.5.5.5
      - numpy==1.26.4
      - open3d==0.19.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - plotly==6.5.2
      - polyscope==2.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.36.2
      - retrying==1.4.2
      - rpds-py==0.27.1
      - safe-gpu==2.0.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - torch-geometric==2.6.1
      - traitlets==5.14.3
      - typer-slim==0.21.1
      - tzdata==2025.3
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - yarl==1.22.0
      - zipp==3.23.0